### PR TITLE
Update loadtype.js

### PR DESCRIPTION
**Pull request by JavaScythe**

### CODE REVIEW

**Comment by JavaScythe** [comment]
merge it retards

**Comment by Cattn** [comment]
no someone check it first

**Comment by Nailington** [comment]
@Cattn I actually have zero clue on how to merge this into a new branch, as @JavaScythe decided to make it merge to gh-pages when he made it

**Comment by Cattn** [comment]
https://github.com/JavaScythe/gba-hst/tree/patch-1 open this in github desktop

**Comment by JavaScythe** [comment]
kys

**Pull request closed without merging**
